version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hung-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ih7o9d6osmmo"
s3_prefix = "hung-test"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
